In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('loan_data.csv')
df.head()

,applicant_id,name,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,APP1170,Raj Smith,NaN,"$66,400",NaN,89100.0,Unemployed,No,Female,Rejected
1,APP1177,Omar Silva,25.0,"$75,700",645.0,228600.0,Employed,NaN,Male,Approved
2,APP1132,Mei Khan,24.0,"$26,400",580.0,5000.0,employed,Yes,Female,Approved
3,APP1193,Liam Ali,28.0,"$78,500",NaN,272600.0,Employed,No,Female,Approved
4,APP1102,Raj Kumar,35.0,NaN,573.0,159000.0,employed,N,Female,Rejected

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   applicant_id       212 non-null    str
 1   name               212 non-null    str
 2   age                194 non-null    float64
 3   income             202 non-null    str
 4   credit_score       195 non-null    float64
 5   loan_amount        212 non-null    float64
 6   employment_status  201 non-null    str
 7   married            200 non-null    str
 8   gender             202 non-null    str
 9   approved           212 non-null    str
dtypes: float64(3), str(7)
memory usage: 26.2 KB

In [4]:
df.describe()

              age  credit_score    loan_amount
count  194.000000    195.000000     212.000000
mean    43.448454    648.574359  152261.792453
std     20.945523    132.753971   85665.271670
min     -5.000000      0.000000    5000.000000
25%     31.000000    582.500000   88950.000000
50%     41.000000    652.000000  155800.000000
75%     54.000000    737.500000  207575.000000
max    200.000000    850.000000  448800.000000

In [5]:
df.shape

(212, 10)

In [6]:
df.isnull().sum()

applicant_id          0
name                  0
age                  18
income               10
credit_score         17
loan_amount           0
employment_status    11
married              12
gender               10
approved              0
dtype: int64

In [7]:
df.head()

,applicant_id,name,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,APP1170,Raj Smith,NaN,"$66,400",NaN,89100.0,Unemployed,No,Female,Rejected
1,APP1177,Omar Silva,25.0,"$75,700",645.0,228600.0,Employed,NaN,Male,Approved
2,APP1132,Mei Khan,24.0,"$26,400",580.0,5000.0,employed,Yes,Female,Approved
3,APP1193,Liam Ali,28.0,"$78,500",NaN,272600.0,Employed,No,Female,Approved
4,APP1102,Raj Kumar,35.0,NaN,573.0,159000.0,employed,N,Female,Rejected

#### 1. Removed Unnecessary columns

In [8]:
df = df.drop(columns=['applicant_id', 'name'])
df.head()

,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,NaN,"$66,400",NaN,89100.0,Unemployed,No,Female,Rejected
1,25.0,"$75,700",645.0,228600.0,Employed,NaN,Male,Approved
2,24.0,"$26,400",580.0,5000.0,employed,Yes,Female,Approved
3,28.0,"$78,500",NaN,272600.0,Employed,No,Female,Approved
4,35.0,NaN,573.0,159000.0,employed,N,Female,Rejected

#### 2. Duplicates

In [9]:
duplicate_rows = df[df.duplicated(keep=False)]
duplicate_rows

,age,income,credit_score,loan_amount,employment_status,married,gender,approved
3,28.0,"$78,500",NaN,272600.0,Employed,No,Female,Approved
5,26.0,"$12,000",574.0,78000.0,Unemployed,Y,Male,Rejected
13,47.0,"$56,600",627.0,249000.0,employed,no,M,Approved
16,60.0,"$57,700",806.0,117600.0,self employed,NaN,Male,Approved
30,55.0,"$47,600",632.0,113300.0,employed,Yes,Female,Rejected
38,NaN,"$61,300",745.0,70700.0,Self-Employed,yes,male,Approved
60,36.0,34100,647.0,277800.0,employed,No,M,Rejected
64,NaN,"$61,300",745.0,70700.0,Self-Employed,yes,male,Approved
69,50.0,"$26,300",624.0,129000.0,Self Employed,Yes,F,Rejected
73,28.0,"$78,500",NaN,272600.0,Employed,No,Female,Approved
94,NaN,"$12,000",786.0,126300.0,employed,no,Male,Rejected
106,36.0,34100,647.0,277800.0,employed,No,M,Rejected
118,39.0,"$62,500",834.0,159800.0,Employed,Yes,Female,Approved
119,37.0,"$46,400",760.0,140900.0,employed,N,Male,Approved
129,60.0,"$57,700",806.0,117600.0,self employed,NaN,Male,Approved
134,42.0,"$55,400",582.0,218600.0,NaN,NaN,Male,Rejected
154,42.0,"$55,400",582.0,218600.0,NaN,NaN,Male,Rejected
160,37.0,"$46,400",760.0,140900.0,employed,N,Male,Approved
161,50.0,"$26,300",624.0,129000.0,Self Employed,Yes,F,Rejected
165,47.0,"$56,600",627.0,249000.0,employed,no,M,Approved
176,55.0,"$47,600",632.0,113300.0,employed,Yes,Female,Rejected
177,NaN,"$12,000",786.0,126300.0,employed,no,Male,Rejected
203,26.0,"$12,000",574.0,78000.0,Unemployed,Y,Male,Rejected
207,39.0,"$62,500",834.0,159800.0,Employed,Yes,Female,Approved

In [10]:
df.drop_duplicates(inplace=True)

#### 3. Formatting the income column

In [11]:
df['income'] = (
    df['income'].astype(str)
    .str.replace(r'[$,]', '', regex=True)
    .str.strip()
)

df.head()

,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,NaN,66400,NaN,89100.0,Unemployed,No,Female,Rejected
1,25.0,75700,645.0,228600.0,Employed,NaN,Male,Approved
2,24.0,26400,580.0,5000.0,employed,Yes,Female,Approved
3,28.0,78500,NaN,272600.0,Employed,No,Female,Approved
4,35.0,NaN,573.0,159000.0,employed,N,Female,Rejected

In [12]:
df.info()

<class 'pandas.DataFrame'>
Index: 200 entries, 0 to 211
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                184 non-null    float64
 1   income             190 non-null    str
 2   credit_score       184 non-null    float64
 3   loan_amount        200 non-null    float64
 4   employment_status  190 non-null    str
 5   married            190 non-null    str
 6   gender             190 non-null    str
 7   approved           200 non-null    str
dtypes: float64(3), str(5)
memory usage: 19.5 KB

#### 4. Normalizing the gender and married columns

In [13]:
df.gender.value_counts()

gender
Male      37
M         34
female    34
male      31
F         28
Female    26
Name: count, dtype: int64

In [14]:
df['gender'] = df['gender'].map(
    {'male': 'Male', 'Male': 'Male', 'm': 'Male', 'M': 'Male', 'female': 'Female', 'Female': 'Female', 'f': 'Female', 'F': 'Female'}
)

In [15]:
df['married'].value_counts()

married
Yes    54
No     34
Y      33
yes    27
N      24
no     18
Name: count, dtype: int64

In [16]:
df['married'] = df['married'].map(
    {'yes': 'Yes', 'Yes': 'Yes', 'y': 'Yes', 'Y': 'Yes', 'no': 'No', 'No': 'No', 'n': 'No', 'N': 'No'}
)

In [17]:
df['employment_status'].value_counts()

employment_status
employed         61
Employed         49
Self-Employed    20
Unemployed       17
unemployed       15
self employed    14
Self Employed    14
Name: count, dtype: int64

In [18]:
df['employment_status'] = df['employment_status'].map(
    {
        'employed': 'Employed',
        'Employed': 'Employed',
        'self employed': 'Self-Employed',
        'self-employed': 'Self-Employed',
        'Self-Employed': 'Self-Employed',
        'Self Employed': 'Self-Employed',
        'unemployed': 'Unemployed',
        'Unemployed': 'Unemployed',
    }
)

#### 5. Formatting age and credit score column

In [19]:
df.describe()

              age  credit_score    loan_amount
count  184.000000    184.000000     200.000000
mean    43.527174    645.951087  151629.500000
std     21.366674    134.420646   86473.742375
min     -5.000000      0.000000    5000.000000
25%     31.000000    581.500000   88250.000000
50%     41.000000    656.000000  157450.000000
75%     54.000000    729.250000  205700.000000
max    200.000000    850.000000  448800.000000

In [20]:
df.loc[(df['age'] < 18) | (df['age'] > 100), 'age'] = np.nan

In [21]:
df.loc[(df['credit_score'] < 300) | (df['credit_score'] > 850), 'credit_score'] = np.nan

In [22]:
df.isna().sum()

age                  20
income               10
credit_score         20
loan_amount           0
employment_status    10
married              10
gender               10
approved              0
dtype: int64

In [23]:
df.age.median()

np.float64(41.0)

In [24]:
columns = ['age', 'income', 'credit_score', 'loan_amount']

for c in columns:
    df[c] = pd.to_numeric(df[c], errors='coerce')
    df[c] = df[c].fillna(df[c].median())

Here,
we are using MODE, because we are having text

In [25]:
df.employment_status.mode()

0    Employed
Name: employment_status, dtype: str

In [26]:
df = df.dropna(subset=['gender', 'married', 'employment_status'])

In [27]:
df.isna().sum()

age                  0
income               0
credit_score         0
loan_amount          0
employment_status    0
married              0
gender               0
approved             0
dtype: int64

In [31]:
df.head(5)

,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,41.0,66400.0,665.5,89100.0,Unemployed,No,Female,0
2,24.0,26400.0,580.0,5000.0,Employed,Yes,Female,1
3,28.0,78500.0,665.5,272600.0,Employed,No,Female,1
4,35.0,51150.0,573.0,159000.0,Employed,No,Female,0
5,26.0,12000.0,574.0,78000.0,Unemployed,Yes,Male,0

In [30]:
df['approved'] = df['approved'].map(
    {'Approved': 1, 'Rejected': 0}
)

#### 6. One-Hot Encoding

In [35]:
df = pd.get_dummies(df, columns=['gender', 'employment_status', 'married'], drop_first=True)
df.head()

,age,income,credit_score,loan_amount,approved,gender_Male,employment_status_Self-Employed,employment_status_Unemployed,married_Yes
0,-0.093148,0.682279,0.021636,-0.744086,0,False,False,True,False
2,-1.548956,-1.214403,-0.929729,-1.699486,1,False,False,False,True
3,-1.206413,1.256025,0.021636,1.340528,1,False,False,False,False
4,-0.606962,-0.040831,-1.007618,0.049999,0,False,False,False,False
5,-1.377685,-1.897209,-0.996491,-0.870185,0,True,False,True,True

#### 7. Using StandardScaler to scale the age, income, credit_score, loan_amount columns

In [33]:
num_cols = ['age', 'income', 'credit_score', 'loan_amount']

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[num_cols] = scaler.fit_transform(df[num_cols])

df[num_cols].head()

        age    income  credit_score  loan_amount
0 -0.093148  0.682279      0.021636    -0.744086
2 -1.548956 -1.214403     -0.929729    -1.699486
3 -1.206413  1.256025      0.021636     1.340528
4 -0.606962 -0.040831     -1.007618     0.049999
5 -1.377685 -1.897209     -0.996491    -0.870185

In [34]:
df[num_cols].describe()

                age        income  credit_score   loan_amount
count  1.710000e+02  1.710000e+02  1.710000e+02  1.710000e+02
mean   1.558208e-17  1.947760e-17 -5.194026e-18 -2.337312e-17
std    1.002937e+00  1.002937e+00  1.002937e+00  1.002937e+00
min   -1.805864e+00 -1.897209e+00 -2.654424e+00 -1.699486e+00
25%   -7.782341e-01 -6.809616e-01 -7.350048e-01 -7.565821e-01
50%   -9.314771e-02 -4.083135e-02  2.163597e-02  8.748753e-02
75%    7.632103e-01  6.396034e-01  7.059508e-01  6.185811e-01
max    1.876476e+00  2.465160e+00  2.074580e+00  3.342211e+00

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X = df.drop(columns=['approved'])
y = df['approved']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

print(f"Test Accuracy: {model.score(X_test, y_test):.2f}")

Test Accuracy: 0.69

In [40]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

report = classification_report(y_test, y_pred)

print(report)

              precision    recall  f1-score   support

           0       0.73      0.76      0.74        21
           1       0.62      0.57      0.59        14

    accuracy                           0.69        35
   macro avg       0.67      0.67      0.67        35
weighted avg       0.68      0.69      0.68        35